name: Sync Forks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-forks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync forks
        uses: tgymnich/fork-sync@v2.0.10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}