name: Sync Fork with Upstream

on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:

# Only run this workflow on fork repositories, not on the original repository
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-with-upstream:
    # Only run this job if this is a fork repository
    if: github.event.repository.fork == true
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the fork repository
      - name: Checkout fork repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: false
      
      # Step 2: Sync fork with upstream repository
      - name: Sync fork with upstream
        uses: tgymnich/fork-sync@v1.6
        with:
          owner: JiuNian090
          repo: workcum
          base: main
          head: main
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # Step 3: Handle sync failures
      - name: On sync failure
        if: failure()
        run: |
          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，详细教程请查看项目README.md"
          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the project README.md for instructions."
          exit 1